# 项目相关配置
ruoyi:
  # 名称
  name: CodeDesign
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/codedesign/uploadPath
  # 获取ip地址开关
  addressEnabled: false

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

# 日志配置
logging:
  level:
    com.hulang: debug
    org.springframework: warn